### PR TITLE
Dashboard component, Moralis addition, consistent styling

### PR DESCRIPTION
**Pull request by pulkitvyas08**
The PR:
- Adds Moralis API for MetaMask integration #3 
- Fixes consistent styling issues with the UI #8 
- Adds user dashboard component #10 
- Adds sidebar component, a basic blog editor component, updates navbar component

### CODE REVIEW

**Review by maektwain — CHANGES_REQUESTED** [review]
In my opinion , the isAuth for the URL should be removed as long as fetching or reading of data can be open since there is no interaction, and when it comes to interaction of any writing of states that happen to the Contract then we can use these methods.

**Comment by pulkitvyas08** [comment]
`IsAuthenticated` is not just for URL and access but also controls whether certain UI components should be displayed or not (modals, etc.) as we have not implemented or used a 3rd party token/session-based auth system. So for the time being this might be good enough

**Comment by ishubhamk-cynsar** [comment]
> `IsAuthenticated` is not just for URL and access but also controls whether certain UI components should be displayed or not (modals, etc.) as we have not implemented or used a 3rd party token/session-based auth system. So for the time being this might be good enough

That is fine for now, since we are just starting out, we will revisit it later as we progress

**Comment by ishubhamk-cynsar** [comment]
Had a discussion with @pulkitvyas08 around this pr, there are couple of things which will be handled in subsequent pull requests, we will create issues for it. For now since this is an initial setup, pull request is fine and we can proceed with merge so that everyone can sync.

**Pull request merged**
