### PR TITLE
When loading this post and shows empty comment #113

### LINKED ISSUE #113: When loading this post and shows empty comment
https://second.exchange/post/000315ede00e4db3e7f2277d5ca4822b06c3ddee3b930bde4d353ea256cf8c94

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'sub')
    at [postId]-52a5d3d7533fd5c6.js:1:9684
    at u (main-dbd1876fb2decdc0.js:1:94020)
    at Generator._invoke (main-dbd1876fb2decdc0.js:1:95306)
    at a.<computed> [as next] (main-dbd1876fb2decdc0.js:1:94423)
    at d (_app-504ae576f33b6200.js:8:10705)
    at e (_app-504ae576f33b6200.js:8:10902)
    at _app-504ae576f33b6200.js:8:10961
    at new Promise (<anonymous>)
    at _app-504ae576f33b6200.js:8:10843
    at p ([postId]-52a5d3d7533fd5c6.js:1:10056)

### PR DESCRIPTION
**Pull request by thozinza**

### CODE REVIEW

**Comment by saranshisatgit** [comment]
Could you describe what this does?

**Comment by pulkitvyas08** [comment]
> Could you describe what this does?

Hi, what are you referring to?

**Review by pulkitvyas08 — APPROVED** [review]
This was a really simple fix, thanks

**Comment by ThoTrung** [comment]
@pulkitvyas08
Oh sorry, I didn't notice your message.
> Could you describe what this does?

Do you mean the logic of the code?
> getPostComments

This function is called when the variable **pool** is not ready.

**Comment by ThoTrung** [comment]
@pulkitvyas08
Do you need to fix bugs and develop new features for this project?

**Comment by saranshisatgit** [comment]
Yeah, @ThoTrung glad that you are here, it would be great if you could work since you are intended to code join our telegram channel here https://t.me/+gw5l3kJJBYk4YzI9

Lets communicate there are some open arenas.

**Comment by ThoTrung** [comment]
@saranshisatgit 
Oh yeah, sorry for the late reply because our company didn't work at the weekend.
I'm from Zinza Technology and Mrs.Hung (hung@zinza.com.vn) is my boss.
He has already contacted you.

I joined group but didn't see any message

**Comment by ThoTrung** [comment]
@saranshisatgit 
What should I do now?
I will continue to fix issues or code new features. But I don't know the spec, Could you give me the spec?
And I am the developer of Zinza company. Could you contact Mrs. Hung first?

**Pull request merged**
